export const images = {
  logo: require("./assets/logos/logoplaystation.png"),
  standardps5: require("./assets/items/standardps5.jpg"),
  standardps5gow: require("./assets/items/standardps5-gow.jpg"),
  digitalps5: require("./assets/items/digitalps5.jpg"),
  digitalps5gow: require("./assets/items/digitalps5-gow.jpg"),
  dualsensewhite: require("./assets/items/dualsensewhite.jpg"),
  dualsenseblack: require("./assets/items/dualsenseblack.jpg"),
  pulse3dblack: require("./assets/items/pulse3dblack.jpg"),
  pulse3dcamo: require("./assets/items/pulse3dcamo.jpg"),
  dualsensechargingstation: require("./assets/items/dualsensechargingstation.jpg"),
  dualsenseedgewhite: require("./assets/items/dualsenseedgewhite.jpg"),
  eldenring: require("./assets/items/eldenring.jpg"),
  hogwartslegacy: require("./assets/items/hogwartslegacy.jpg"),
  granturismo7: require("./assets/items/granturismo7.jpg"),
  forbiddenwest: require("./assets/items/forbiddenwest.jpg"),
  unchartedlegacy: require("./assets/items/unchartedlegacy.jpg"),
  shirt1: require("./assets/items/playstationlogoshirt.jpg"),
  necessarirexgen: require("./assets/items/pencils1.jpg"),
  pscapjapan: require("./assets/items/cap1.jpg"),
  psbedjapan: require("./assets/items/bed1.jpg"),
};
