export const images = {
  defaultProfile: require("./assets/defaultProfile.jpeg"),
  logo: require("./assets/logos/logoplaystation.png"),
  psstorelogo: require("./assets/logos/psstore.png"),
  standardps5: require("./assets/items/standardps5.png"),
  standardps5gow: require("./assets/items/standardps5-gow.png"),
  digitalps5: require("./assets/items/digitalps5.png"),
  digitalps5gow: require("./assets/items/digitalps5-gow.png"),
  dualsensewhite: require("./assets/items/dualsensewhite.png"),
  dualsenseblack: require("./assets/items/dualsenseblack.png"),
  pulse3dblack: require("./assets/items/pulse3dblack.png"),
  pulse3dcamo: require("./assets/items/pulse3dcamo.png"),
  dualsensechargingstation: require("./assets/items/dualsensechargingstation.png"),
  dualsenseedgewhite: require("./assets/items/dualsenseedgewhite.png"),
  eldenring: require("./assets/items/eldenring.png"),
  hogwartslegacy: require("./assets/items/hogwartslegacy.png"),
  granturismo7: require("./assets/items/granturismo7.png"),
  forbiddenwest: require("./assets/items/forbiddenwest.png"),
  unchartedlegacy: require("./assets/items/unchartedlegacy.png"),
  shirt1: require("./assets/items/playstationlogoshirt.png"),
  necessarirexgen: require("./assets/items/pencils1.png"),
  pscapjapan: require("./assets/items/cap1.png"),
  psbedjapan: require("./assets/items/bed1.png"),
};
